name: Build and Test Jolt-Atlas
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**', main]

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: cargo clippy
        run: cargo clippy --all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Run zkml-jolt-core tests
        run: cargo nextest run --release -p zkml-jolt-core

  test-onnx-tracer:
    name: Test onnx-tracer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run onnx-tracer tests
        working-directory: ./onnx-tracer
        run: cargo test

  build-wasm:
    name: Build Wasm
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "" # Override global RUSTFLAGS to allow warnings for WASM build
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Build Wasm
        working-directory: ./onnx-tracer
        run: cargo build --release --target wasm32-unknown-unknown